### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by rbradford** [weltling/meta-cloud-hypervisor#1]
@weltling Do you plan to update this to a newer version?

**Comment by weltling** [comment]
@rbradford we're now at 20.2 thanks to @russell-islam :) More updates to follow.

Thanks

**Comment by russell-islam** [comment]
Updated to 20.2 and updated ovmf as well.

**Comment by weltling** [comment]
I guess we can close this as the updates are being produced so we're now at the latest stage.

Thanks
